# Generated by Django 3.1.5 on 2021-01-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes',
            new_name='votes_to_skip',
        ),
    ]
